# Form implementation generated from reading ui file 'D:\mhe\GitHub\K224161818_ML\HelloWorld\HelloWorldDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Minhe_HelloWorld(object):
    def setupUi(self, Minhe_HelloWorld):
        Minhe_HelloWorld.setObjectName("Minhe_HelloWorld")
        Minhe_HelloWorld.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Minhe_HelloWorld.resize(400, 300)
        Minhe_HelloWorld.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Minhe_HelloWorld)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Minhe_HelloWorld)
        self.label.setGeometry(QtCore.QRect(80, 70, 231, 111))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Minhe_HelloWorld)
        self.buttonBox.accepted.connect(Minhe_HelloWorld.accept) # type: ignore
        self.buttonBox.rejected.connect(Minhe_HelloWorld.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Minhe_HelloWorld)

    def retranslateUi(self, Minhe_HelloWorld):
        _translate = QtCore.QCoreApplication.translate
        Minhe_HelloWorld.setWindowTitle(_translate("Minhe_HelloWorld", "Mhe - HelloWorld"))
        self.label.setText(_translate("Minhe_HelloWorld", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ff00e6;\">Hello World</span></p></body></html>"))
