# Form implementation generated from reading ui file 'D:\mhe\GitHub\ML_K224161818\Salesmanagement\ui\MainProgramMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 80, 461, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuH_th_ng = QtWidgets.QMenu(parent=self.menubar)
        self.menuH_th_ng.setObjectName("menuH_th_ng")
        self.menuQu_n_l = QtWidgets.QMenu(parent=self.menubar)
        self.menuQu_n_l.setObjectName("menuQu_n_l")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionthongtintaikhoan = QtGui.QAction(parent=MainWindow)
        self.actionthongtintaikhoan.setObjectName("actionthongtintaikhoan")
        self.actiondoimatkhau = QtGui.QAction(parent=MainWindow)
        self.actiondoimatkhau.setObjectName("actiondoimatkhau")
        self.actioncauhinhhethong = QtGui.QAction(parent=MainWindow)
        self.actioncauhinhhethong.setObjectName("actioncauhinhhethong")
        self.actionthoatphanmem = QtGui.QAction(parent=MainWindow)
        self.actionthoatphanmem.setObjectName("actionthoatphanmem")
        self.actionQly_sp_danh_mucj = QtGui.QAction(parent=MainWindow)
        self.actionQly_sp_danh_mucj.setObjectName("actionQly_sp_danh_mucj")
        self.actionQly_don_hang = QtGui.QAction(parent=MainWindow)
        self.actionQly_don_hang.setObjectName("actionQly_don_hang")
        self.actionQly_nhan_vien = QtGui.QAction(parent=MainWindow)
        self.actionQly_nhan_vien.setObjectName("actionQly_nhan_vien")
        self.menuH_th_ng.addAction(self.actionthongtintaikhoan)
        self.menuH_th_ng.addAction(self.actiondoimatkhau)
        self.menuH_th_ng.addAction(self.actioncauhinhhethong)
        self.menuH_th_ng.addAction(self.actionthoatphanmem)
        self.menuQu_n_l.addAction(self.actionQly_sp_danh_mucj)
        self.menuQu_n_l.addAction(self.actionQly_don_hang)
        self.menuQu_n_l.addAction(self.actionQly_nhan_vien)
        self.menubar.addAction(self.menuH_th_ng.menuAction())
        self.menubar.addAction(self.menuQu_n_l.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đây là màn hình chính"))
        self.menuH_th_ng.setTitle(_translate("MainWindow", "Hệ thống"))
        self.menuQu_n_l.setTitle(_translate("MainWindow", "Quản lý"))
        self.actionthongtintaikhoan.setText(_translate("MainWindow", "Thong tin tai khoan"))
        self.actionthongtintaikhoan.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actiondoimatkhau.setText(_translate("MainWindow", "Doi mat khau"))
        self.actioncauhinhhethong.setText(_translate("MainWindow", "Cau hinh he thong"))
        self.actionthoatphanmem.setText(_translate("MainWindow", "Thoat phan mem"))
        self.actionQly_sp_danh_mucj.setText(_translate("MainWindow", "Qly sp - danh muc"))
        self.actionQly_don_hang.setText(_translate("MainWindow", "Qly don hang"))
        self.actionQly_nhan_vien.setText(_translate("MainWindow", "Qly nhan vien"))
